# my_string = input('Введите произвольный текст: ')
# print(len(my_string))
# print(my_string.upper())
# print(my_string.lower())
# print(my_string.replace(' ',''))
# print(my_string[0])
# print(my_string[-1])

name = input("Введите ваше имя: ")
print('Здравствуйте ' + name + '!')
yar = int(input('В каком году вы родились? '))
print('Сегодня вам ', 2024 - yar, 'лет')